Create test_filter.py
Hipo/university-domains-list pull request #510
Opened 2023-06-12 20:43 UTC by zoharasulin

HI  .
This PR was sent as part of course OSDC taught by: @szabgab.
I add file test to your code filter.py.
I think this tests can help your project when in further- you change the code or maybe add more features.
I see your project and project API that base on your code and it very intersting.
I wonder that was in your list json universities and colleges from Israel(my country :))
Nice job!

2023-06-13 04:30 UTC, szabgab commented
I like these tests very much!

2023-06-14 08:14 UTC, yigitguler commented
Hello! Thank you very much for this contribution. 
However, I suspect it is opened to the wrong repository.
This is the repository of the JSON file. The API is located here: https://github.com/Hipo/university-domains-list-api/
Also the build fails to work. I assume this is related with the repository difference.

2023-06-15 05:21 UTC, zoharasulin commented
Hello @yigitguler
First of all I'm sorry it fell.
I did tests and saw that everything was running.
Probably something small in the import.
Regarding what you say, it has nothing to do with your script, I simply saw a filter.py in repo, according to what I understand, sorts the universities and etc.
This is not true?

2025-09-10 09:09 UTC, ceydaduzgec requested changes

2025-09-10 09:09 UTC, ceydaduzgec commented on tests/test_filter.py
> +from university-domains-list import filter
Hello @zoharasulin thank your for your PR. I think we should change this import to `from filter import country_filter` Since `country_filter` is not imported in this file.

2026-04-21 00:14 UTC, closed without merging